name: MkDocs Build and Deploy
on:
  push:
    branches:
      - master 
      - main

permissions:
  contents: write

jobs:
  deploy_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'

      - name: Print Python Version
        run: python -c "import sys; print(sys.version)"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build Mkdocs
        run: mkdocs build --verbose --clean --strict

      - name: Deploy Documentation
        run: mkdocs gh-deploy --force
